set(SEARCH_PATHS
    /usr
    /usr/local
    )

find_path(SDL2_INCLUDE_DIR SDL2/SDL.h PATH_SUFFIXES include PATHS ${SEARCH_PATHS})
find_path(SDL2_INCLUDE_DIR_NOPREFIX SDL.h PATH_SUFFIXES include/SDL2 PATHS ${SEARCH_PATHS})
find_library(SDL2_LIBRARY NAMES SDL2 PATH_SUFFIXES lib lib64 lib/x64 PATHS ${SEARCH_PATHS})

add_library(sdl2::sdl2 UNKNOWN IMPORTED)
set_target_properties(sdl2::sdl2 PROPERTIES IMPORTED_LOCATION "${SDL2_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${SDL2_INCLUDE_DIR}")

add_library(sdl2::sdl2-noprefix UNKNOWN IMPORTED)
set_target_properties(sdl2::sdl2-noprefix PROPERTIES IMPORTED_LOCATION "${SDL2_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${SDL2_INCLUDE_DIR_NOPREFIX}")

find_path(SDL2_TTF_INCLUDE_DIR SDL2/SDL_ttf.h PATH_SUFFIXES include PATHS ${SEARCH_PATHS})
find_library(SDL2_TTF_LIBRARY NAMES SDL2_ttf PATH_SUFFIXES lib lib64 lib/x64 PATHS ${SEARCH_PATHS})

add_library(sdl2::sdl2-ttf UNKNOWN IMPORTED)
set_target_properties(sdl2::sdl2-ttf PROPERTIES IMPORTED_LOCATION "${SDL2_TTF_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${SDL2_TTF_INCLUDE_DIR}")

find_path(SDL2_IMAGE_INCLUDE_DIR SDL2/SDL_image.h PATH_SUFFIXES include PATHS ${SEARCH_PATHS})
find_library(SDL2_IMAGE_LIBRARY NAMES SDL2_image PATH_SUFFIXES lib lib64 lib/x64 PATHS ${SEARCH_PATHS})

add_library(sdl2::sdl2-image UNKNOWN IMPORTED)
set_target_properties(sdl2::sdl2-image PROPERTIES IMPORTED_LOCATION "${SDL2_IMAGE_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${SDL2_IMAGE_INCLUDE_DIR}")

find_path(FREETYPE_INCLUDE_DIR freetype/freetype.h PATH_SUFFIXES include include/freetype2 PATHS ${SEARCH_PATHS})
find_library(FREETYPE_LIBRARY NAMES freetype PATH_SUFFIXES lib lib64 lib/x64 PATHS ${SEARCH_PATHS})

add_library(freetype::freetype UNKNOWN IMPORTED)
set_target_properties(freetype::freetype PROPERTIES IMPORTED_LOCATION "${FREETYPE_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${FREETYPE_INCLUDE_DIR}")

find_path(GLEW_INCLUDE_DIR GL/glew.h PATH_SUFFIXES include PATHS ${SEARCH_PATHS})
find_library(GLEW_LIBRARY NAMES GLEW PATH_SUFFIXES lib lib64 lib/x64 PATHS ${SEARCH_PATHS})

add_library(glew::glew UNKNOWN IMPORTED)
set_target_properties(glew::glew PROPERTIES IMPORTED_LOCATION "${GLEW_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${GLEW_INCLUDE_DIR}")
